### ISSUE TITLE
modsec-shared-collections

### ISSUE THREAD

**Issue by alpinelink** [karljohns0n/nginx-more#12]
I note https://github.com/SpiderLabs/ModSecurity-nginx/issues/174

Thanks for your work on this repo, it is a real timesaver!

I didn't understand the closing status of your issue. It's quite a big problem to have these files all over the filesystem. I did want to use modsecurity so not loading the module isn't a good solution.

I didn't quite understand how this might be normal. I realise it's somewhat outside your control but I'm asking if you found a solution.

**Comment by karljohns0n** [comment]
Thanks for using nginx-more!

Unfortunately I can't do nothing about this behavior except packaging libmodsecurity without [LMDB](https://github.com/karljohns0n/pkg-libmodsecurity/blob/master/SPECS/libmodsecurity.spec#L67), which I tried and worked well, but I think people expect LMDB to be available so we have to deal with these files.

Hopefully the ModSecurity team can workaround this behavior in futur release or at least set a specific path for these files instead of spamming the filesystem..

**Comment by alpinelink** [comment]
thanks, I did fully understand some of this was outside of your direct control!

That would be my approach, drop LMDB but I'd rather not drop using your repo. I'll keep a watch on progress!

thanks!

**Comment by karljohns0n** [comment]
Closing this issue as it's unfortunately on ModSecurity side.

**Comment by phpstatic** [comment]
Maybe add workaround to create the file in /tmp folder, or an option to set the folder.
 
The current status made the project is create by amateur.
