### ISSUE TITLE
Error: nginx-more conflicts with 1:nginx-1.16.1-1.el7.x86_64

### ISSUE THREAD

**Issue by nguyenhuutinh** [karljohns0n/nginx-more#6]
HI Karl
How to resolve this issue

Error: nginx-more conflicts with 1:nginx-1.16.1-1.el7.x86_64
?
I see your comment but don't understand.

tried --skip-broken but did not work

**Comment by karljohns0n** [comment]
You cannot install both nginx and nginx-more on the same system because both provide nginx. You have to choose between nginx package from EPEL, from Nginx repo, or nginx-more which contains additional modules over the others and which is built on recent GCC version.

If it's a new system, you can remove nginx and install nginx-more with yum swap:

```
yum swap nginx nginx-more 
```

**Comment by karljohns0n** [comment]
Hi, I've updated the README to specify that both nginx-more and nginx package cannot be installed on the same system, see commit 90b362e.

Karl
